TASK: pmm
PRECISION: float64
METRICS_BASE: binary
SEED: 317
DATA_RELOAD: True
DATASET:
  type: SBIFaceForensic
  TRAIN: True #Switch to True for training mode, False for testing mode
  COMPRESSION: c0
  IMAGE_SUFFIX: png
  NUM_WORKERS: 16
  PIN_MEMORY: False
  IMAGE_SIZE: [384, 384]
  HEATMAP_SIZE: [96, 96] #[IMAGE_SIZE//4, IMAGE_SIZE//4]
  SIGMA: 2
  ADAPTIVE_SIGMA: True
  HEATMAP_TYPE: gaussian
  SPLIT_IMAGE: False
  PMM:
    DEGRADATIONS:
      type: ours
      degradations_p: 0.5
      val_degradations_p: 0.5
      degradations_strength: 0.5
      distractor_p: 0.2
    BLENDING:
      poisson_prob: 0.5
    MASKS:
      small_masks: False
      binomial_masks: False
      facepart_masks: True
    GENERATED:
      gan: 0
      sd: 0
    SBI:
      p_factor: 1
  DATA:
    TYPE: frames
    SAMPLES_PER_VIDEO: 
      ACTIVE: True
      TRAIN: 8 # Dynamically random number of frames in each epoch
      VAL: 8
      TEST: 32
    TRAIN:
      NAME: FF++ # This field to define datasets that can be used to train/in-dataset/cross-dataset evaluation
      ROOT: /data/FaceForensics++/
      # ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c0/
      FROM_FILE: True
      FAKETYPE: [Original] # [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
      # ANNO_FILE: train/frames/FaceXRay/train_FF_FaceXRay.json
      ANNO_FILE: processed_data/c23/train_FaceForensics_Original_81.json
      LABEL_FOLDER: [real, fake]
    VAL:
      NAME: FF++ # This field to define datasets that can be used to train/in-dataset/cross-dataset evaluation
      ROOT: /data/FaceForensics++/
      FROM_FILE: True
      FAKETYPE: [Original, Deepfakes, Face2Face, FaceSwap, NeuralTextures] # Choosing Deepfake techniques to be loaded for dataloader
      # ANNO_FILE: val/frames/FaceXRay/val_FF_FaceXRay.json
      ANNO_FILE: processed_data/c23/val_FaceForensics_Original_81.json
      LABEL_FOLDER: [real, fake]
    TEST:
      NAME: DFDCP
      # ROOT: /home/users/<user>/data/FaceForensics++/c0/
      ROOT: /data/LAA-dataset/DFDCP
      # ROOT: /data/LAA-dataset/DFDC
      # ROOT: /data/LAA-dataset/Celeb-DF-v2
      FROM_FILE: False
      # FAKETYPE: [original, Deepfakes]
      # FAKETYPE: [original, Deepfakes, Face2Face, FaceSwap, NeuralTextures]
      # FAKETYPE: [Celeb-real, Celeb-synthesis, YouTube-real]
      FAKETYPE: [method_A, method_B, original_videos]
      # FAKETYPE: ["0", "1"]
      # FAKETYPE: [DeepFakeDetection_original, DeepFakeDetection]
      # FAKETYPE: [fake_test, real_test]
      ANNO_FILE: processed_data/c0/test_DFDCP_original_videos_81.json
      LABEL_FOLDER: [real, fake]
  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [384, 384, 0] #h, w, p=probability. If no affine transform, set p=1
      normalize: 0
      horizontal_flip: 0.5
      cropping: [0.15, 0.5] #Format: [crop_limit, prob]
      scale: [0.15, 0.5] #Format: [scale_limit, prob]
      rand_erasing: [0.5, 1] #Format: [p, max_count]
    color:
      type: ColorJitterTransform
      clahe: 0.0
      colorjitter: 0.3
      gaussianblur: 0.3
      gaussnoise: 0.3
      jpegcompression: [0.5, 40, 100] # prob, lower and upper quality respectively
      rgbshift: 0.3
      randomcontrast: 0.0
      randomgamma: 0.5
      randombrightness: 1
      huesat: 1
    normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
  DEBUG: False
  DYNAMIC_FXRAY: True
MODEL:
  type: PoseEfficientNet
  model_name: efficientnet-b4
  num_layers: B4
  include_top: False
  include_hm_decoder: True
  head_conv: 64
  use_c2: False
  use_c3: True
  use_c4: True
  use_c51: True
  efpn: True
  tfpn: False
  se_layer: False
  heads:
    hm: 1
    cls: 1
    cstency: 256
  INIT_WEIGHTS:
    pretrained: True
    advprop: True
TRAIN:
  gpus: [0]
  batch_size: 6
  lr: 0.00002
  epochs: 160
  begin_epoch: -1
  warm_up: 0
  every_val_epochs: 1
  loss:
    type: CombinedFocalLoss
    use_target_weight: False
    cls_lmda: 1
    dst_hm_cls_lmda: 0
    offset_lmda: 0
    hm_lmda: 10
    cstency_lmda: 100
    mse_reduction: sum
    ce_reduction: mean
  optimizer: SAM
  distributed: False
  pretrained: "pretrained/pmm_best.pth"
  tensorboard: True
  resume: True
  lr_scheduler:
    milestones: [5, 15, 20, 25]
    gamma: 0.5
    type: ReduceLROnPlateau
  freeze_backbone: True
  debug:
    active: False
    save_hm_gt: True
    save_hm_pred: True
TEST:
  gpus: [0]
  subtask: 'eval'
  test_file: ''
  vis_hm: True
  threshold: 0.5
  flip_test: True
  video_level: True
  pretrained: "pretrained/pmm_best.pth"
PREPROCESSING:
  DATASET: DFDC
  SPLIT: test
  ROOT: /data/LAA-dataset/DFDC
  FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  IMAGE_SUFFIX: png
  DATA_TYPE: frames
  LABEL: [real, fake]
  facial_lm_pretrained: pretrained/shape_predictor_68_face_landmarks.dat
  DEBUG: False